apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nop-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: azurefile